# Site settings
title: "Kojuhari Sergiu's blog"
email: kojuharis@yahoo.com
description: "A personal blog powered by Jekyll and GitHub Pages"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kojuharis.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: "Kojuhari Sergiu"
  email: kojuharis@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-slate

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"